import type { Metadata } from "next";
import { Geist, Geist_Mono  , Montserrat , Lora} from "next/font/google";
import "./globals.css";


const geistMons = Montserrat({
  variable: "--font-geist-mons",
  weight:["100" , "200","300" , "400", "500" ,"600" , "700" , "800"],
  subsets: ["latin"],
});

const geistLora = Lora({
  variable: "--font-geist-lora",
  weight:["400", "500" ,"600" , "700"],
  subsets: ["latin"],
  display:'swap'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMons.variable} ${geistLora.variable} overflow-x-hidden  antialiased overscroll-y-none`}
      >
        {children}
      </body>
    </html>
  );
}
